In [1]:
#1. What is a Python library? Why do  we use Python libraries?

#A Python library is a collection of pre-written code and functions that aim to simplify the development process for Python programmers. These libraries provide reusable components and tools to perform various tasks, ranging from basic operations to complex functionalities.
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print("Original array:", arr)

# Perform some operations on the array
arr_squared = np.square(arr)
arr_sum = np.sum(arr)

# Print the results
print("Squared array:", arr_squared)
print("Sum of array elements:", arr_sum)

Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]
Sum of array elements: 15


In [2]:
#2. What is the ^ifference between Numpy array an^ List?
"""NumPy arrays are optimized for numerical computing and offer better performance and memory efficiency compared to 
Python lists, especially for large datasets and mathematical operations. However, Python lists are more flexible and 
suitable for general-purpose programming tasks that don't involve heavy numerical computations."""
import numpy as np

# Creating a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

# Creating a Python list
python_list = [1, 2, 3, 4, 5]

# Accessing elements
print("NumPy array elements:", numpy_array)
print("Python list elements:", python_list)

# Adding elements
numpy_array_sum = numpy_array + 10
python_list_sum = [x + 10 for x in python_list]

print("NumPy array after adding 10:", numpy_array_sum)
print("Python list after adding 10:", python_list_sum)

# Multiplying elements
numpy_array_product = numpy_array * 2
python_list_product = [x * 2 for x in python_list]

print("NumPy array after multiplying by 2:", numpy_array_product)
print("Python list after multiplying by 2:", python_list_product)

# Accessing specific elements
print("First element of NumPy array:", numpy_array[0])
print("First element of Python list:", python_list[0])








NumPy array elements: [1 2 3 4 5]
Python list elements: [1, 2, 3, 4, 5]
NumPy array after adding 10: [11 12 13 14 15]
Python list after adding 10: [11, 12, 13, 14, 15]
NumPy array after multiplying by 2: [ 2  4  6  8 10]
Python list after multiplying by 2: [2, 4, 6, 8, 10]
First element of NumPy array: 1
First element of Python list: 1


In [3]:
#3. Fin^ the shape, size an^ ^imension of the following array?
"""[[1, 2, 3, 4]
    [5, 6, 7, 8],
    [9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Find shape
shape = array.shape

# Find size
size = array.size

# Find dimension
dimension = array.ndim

print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimension of the array:", dimension)

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


In [4]:
#4. Write python co^e to access the first row of the following array?
"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the first row
first_row = array[0]

print("First row of the array:", first_row)

First row of the array: [1 2 3 4]


In [5]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = array[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [6]:
#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
"""[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = array[:, 1::2]

print("Odd-indexed elements from the array:")
print(odd_indexed_elements)

Odd-indexed elements from the array:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
#9. Write co^e to increase the ^imension of the following array?
"""[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase the dimension by adding a new axis
new_array = np.expand_dims(array, axis=-1)

print("Original array shape:", array.shape)
print("New array shape:", new_array.shape)

Original array shape: (3, 4)
New array shape: (3, 4, 1)


In [8]:
#10. How to transpose the following array in NumPy?
"""[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array
transposed_array = array.T

print("Original array:")
print(array)

print("\nTransposed array:")
print(transposed_array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [9]:
#11. Consi^er the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
"""Perform the following operation using Python1
1-Index  wise multiplicatio'
2- Matix multiplicatio'
3-Add both the maticK
4-Subtact matix B om 
5- Diide Matix B by A"""
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_mult = A * B

# Matrix multiplication
matrix_mult = np.dot(A, B.T)  # Assuming you want A multiplied by the transpose of B

# Addition of matrices
matrix_addition = A + B

# Subtraction of matrix B from matrix A
matrix_subtraction = A - B

# Division of matrix B by matrix A
matrix_division = B / A

# Displaying the results
print("Index-wise multiplication:\n", index_wise_mult)
print("\nMatrix multiplication:\n", matrix_mult)
print("\nAddition of matrices:\n", matrix_addition)
print("\nSubtraction of matrix B from matrix A:\n", matrix_subtraction)
print("\nDivision of matrix B by matrix A:\n", matrix_division)

Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of matrix B from matrix A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of matrix B by matrix A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
import numpy as np

# Create an array with a specific byte order
array = np.array([1, 2, 3, 4], dtype='>i4')  # '>i4' specifies big-endian 4-byte integer

# Swap the byte order of the array
swapped_array = array.byteswap()

print("Original array:", array)
print("Swapped array:", swapped_array)

Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


In [11]:
#13. What is the significance of the np.linalg.inv function?
import numpy as np

# Create an array with a specific byte order
array = np.array([1, 2, 3, 4], dtype='>i4')  # '>i4' specifies big-endian 4-byte integer

# Swap the byte order of the array
swapped_array = array.byteswap()

print("Original array:", array)
print("Swapped array:", swapped_array)

Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


In [12]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^?
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [13]:
#15. What is broa^casting in Numpy?
import numpy as np

# Create arrays with different shapes
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

# Add arrays using broadcasting
result = A + B

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nResult of broadcasting:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]

Array B:
[10 20 30]

Result of broadcasting:
[[11 22 33]
 [14 25 36]]
